
default_platform(:mac)

platform :mac do
  before_all do |lane|
    if FastlaneCore::Helper.mac?
      xcversion(version: "~> 12.0.0")
    end
  end

  lane :test do
    scan(scheme: "sshh")
  end
end