name: CI PR

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/**
      - bugfix/**
      - release/**
      - hotfix/**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: macos-10.15
    timeout-minutes: 20
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
       gem install bundler:1.17.2
       bundle config path vendor/bundle
       bundle install --jobs 4 --retry 3

    - name: Test SSHH app
      run:
       bundle exec fastlane test
